# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: featurestore_sql_username
    type: string
    default: "sqladmin"
  - name: featurestore_sql_password
    type: string
    default: "ThisIsNotVerySecure!"
  - name: AAD_CLIENT_ID
    type: string
    default: "d5d082e1-641e-46a3-b681-81c885f355ab"
  - name: AZURE_TENANT_ID
    type: string
    default: "72f988bf-86f1-41af-91ab-2d7cd011db47"
  - name: AZURE_AAD_OBJECT_ID
    type: string
    default: "075c6b3e-1a26-44ff-9118-12cfd9fe75f8"

steps:
  - task: AzureCLI@2
    displayName: "gather required environment variables"
    inputs:
      azureSubscription: "$(ado_service_connection_rg)"
      scriptType: "bash"
      addSpnToEnvironment: true
      scriptLocation: "inlineScript"
      inlineScript: |
        if [[ ! -z "${servicePrincipalId:-}" ]]; then
          SUBSCRIPTION_ID=$(az account show --query 'id' --output tsv)
        else
          SUBSCRIPTION_ID=
        fi

        # Define environment variables
        echo "##vso[task.setvariable variable=SUBSCRIPTION_ID]'$SUBSCRIPTION_ID'"

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: "Create Resources for Feature Store"
    inputs:
      deploymentScope: "Resource Group"
      azureResourceManagerConnection: $(ado_service_connection_rg)
      subscriptionId: $(SUBSCRIPTION_ID)
      action: "Create Or Update Resource Group"
      resourceGroupName: $(terraform_st_resource_group)
      location: $(location)
      templateLocation: "Linked artifact"
      csmFile: "templates/infra/feature_store/azuredeploy.json"
      csmParametersFile: "templates/infra/feature_store/azuredeploy.parameters.json"
      overrideParameters: "-sqlAdminUsername ${{parameters.featurestore_sql_username}} -sqlAdminPassword ${{parameters.featurestore_sql_password}} -resourcePrefix $(feathrprefix) -azureADClientId ${{parameters.AAD_CLIENT_ID}} -azureADTenantId ${{parameters.AZURE_TENANT_ID}}"
      deploymentMode: "Complete"
      deploymentName: "Create Resources for Feature Store"

  - task: AzureCLI@2
    displayName: "Grant Key Vault and Synapse access to selected users"
    inputs:
      azureSubscription: "$(ado_service_connection_rg)"
      scriptType: "bash"
      addSpnToEnvironment: true
      scriptLocation: "inlineScript"
      inlineScript: |
        userId="${featurestore_user}"
        resource_prefix="${feathrprefix}"
        synapse_workspace_name="${resource_prefix}syws"
        keyvault_name="${resource_prefix}kv"
        objectId=$(az ad user show --id $userId --query id -o tsv)
        az keyvault update --name $keyvault_name --enable-rbac-authorization false
        az keyvault set-policy -n $keyvault_name --secret-permissions get list --object-id $objectId
        az role assignment create --assignee $userId --role "Storage Blob Data Contributor"
        az synapse role assignment create --workspace-name $synapse_workspace_name --role "Synapse Contributor" --assignee $userId
